/* participants.js */
/* Практики участников Осеннего ПедСовета */

const practices = [
  {
    name: "Алексеева Светлана",
    position: "",
    tag: "Работа с родителями",
    topic: "Родительский диалог на новый лад: искусство нестандартных собраний",
    bullets: [],
    ppt: "https://disk.yandex.ru/i/LBwoP2PpNfs26w",
  },
  {
    name: "Белозёрова Виктория",
    position: "",
    tag: "Методика",
    topic: "«Ключ к Машуку»: создание разворота лепбука, листа инфографики, квеста, игры и видеоролика",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/YI5azkWM8tTxWg",
  },
  {
    name: "Валивахина Вероника",
    position: "",
    tag: "Краеведение",
    topic: "Культурный код города: школьный музей как пространство идей, исследований и открытий",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/HsTs06DZVu4lJg",
  },
  {
    name: "Долженкова Светлана",
    position: "",
    tag: "Дистанционное обучение",
    topic: "Педагог-дизайнер: конструирование современной образовательной среды на дистанте",
    bullets: [],
    ppt: "https://disk.yandex.ru/i/ziAvjA_lR0lb6A",
  },
  {
    name: "Еликова Ольга",
    position: "",
    tag: "Цифровые технологии",
    topic: "Блог педагога и школьный паблик: пошаговая инструкция (от оформления до создания видеоконтента)",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/nDmYDT9W3D_awA",
  },
  {
    name: "Зобова Юлия",
    position: "",
    tag: "Психология",
    topic: "Собираем образ будущего: нейрографика как инструмент коллективного творчества",
    bullets: [],
    ppt: "https://disk.yandex.ru/i/Ahf3UYrvmKoXzg",
  },
  {
    name: "Крикунова Елена",
    position: "",
    tag: "Цифровые технологии",
    topic: "Цифровой наставник как инструмент формирования поддерживающей образовательной среды: от идеи – к созданию собственного чат-бота в организации",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/H7-yXXibWL8lKg",
  },
  {
    name: "Мотуз Ирина",
    position: "",
    tag: "Организация мероприятий",
    topic: "Формула успешного события «Событие³» – мастер-класс",
    bullets: [],
    ppt: "https://disk.yandex.ru/i/xv9Hwnah1Ajr4Q",
  },
  {
    name: "Сайферт Ирина",
    position: "",
    tag: "Командообразование",
    topic: "«5 островков неэффективности: практикум по построению сильных команд»",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/kOz3CHeNSv2TvQ",
  },
  {
    name: "Шивырталова Елена",
    position: "",
    tag: "Профессиональное развитие",
    topic: "Мастер-класс «Пакет ПРОФИ активирован»",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/U8OQ4fbGgoMNgw",
  },
  {
    name: "Шульженко Анастасия",
    position: "",
    tag: "Методика",
    topic: "Игровая педагогика междисциплинарных уроков: создание рабочего листа для развития когнитивных способностей учащихся",
    bullets: [],
    ppt: "https://disk.yandex.ru/i/IFtXi09KToQOUw",
  },
  {
    name: "Ямилов Юрий",
    position: "",
    tag: "Мотивация",
    topic: "Мотивация – залог успеха!",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/J4e6P-baQYrsSQ",
  }
];
