/* participants.js */
/* Практики участников Осеннего ПедСовета */

const practices = [
  {
    name: "Алексеева Светлана",
    position: "",
    tag: "Работа с родителями",
    topic: "Родительский диалог на новый лад: искусство нестандартных собраний",
    bullets: [],
    ppt: "https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2FAAaNLjCaxToCt5fJwuo16UuVbDj%2B0LwYinoOwpHIXKrkj%2F73c%2BiAsIBlfc%2FZ20twq%2FJ6bpmRyOJonT3VoXnDag%3D%3D%3A%2F112%20ауд.%20АЛЕКСЕЕЕВА.pptx&name=112%20ауд.%20АЛЕКСЕЕЕВА.pptx&nosw=1",
  },
  {
    name: "Белозёрова Виктория",
    position: "",
    tag: "Методика",
    topic: "«Ключ к Машуку»: создание разворота лепбука, листа инфографики, квеста, игры и видеоролика",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/202%20ауд.%20Белозёрова",
  },
  {
    name: "Валивахина Вероника",
    position: "",
    tag: "Краеведение",
    topic: "Культурный код города: школьный музей как пространство идей, исследований и открытий",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/204%20ауд.%20Валивахина",
  },
  {
    name: "Долженкова Светлана",
    position: "",
    tag: "Дистанционное обучение",
    topic: "Педагог-дизайнер: конструирование современной образовательной среды на дистанте",
    bullets: [],
    ppt: "https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2FAAaNLjCaxToCt5fJwuo16UuVbDj%2B0LwYinoOwpHIXKrkj%2F73c%2BiAsIBlfc%2FZ20twq%2FJ6bpmRyOJonT3VoXnDag%3D%3D%3A%2FКонференц-зал_Долженкова_Осенний_ПедСовет_2025.pptx.pdf&name=Конференц-зал_Долженкова_Осенний_ПедСовет_2025.pptx.pdf&nosw=1",
  },
  {
    name: "Еликова Ольга",
    position: "",
    tag: "Цифровые технологии",
    topic: "Блог педагога и школьный паблик: пошаговая инструкция (от оформления до создания видеоконтента)",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/Читальный%20зал_Еликова",
  },
  {
    name: "Зобова Юлия",
    position: "",
    tag: "Психология",
    topic: "Собираем образ будущего: нейрографика как инструмент коллективного творчества",
    bullets: [],
    ppt: "https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2FAAaNLjCaxToCt5fJwuo16UuVbDj%2B0LwYinoOwpHIXKrkj%2F73c%2BiAsIBlfc%2FZ20twq%2FJ6bpmRyOJonT3VoXnDag%3D%3D%3A%2FХолл%202%20этажа_Зобова.pptx&name=Холл%202%20этажа_Зобова.pptx&nosw=1",
  },
  {
    name: "Крикунова Елена",
    position: "",
    tag: "Цифровые технологии",
    topic: "Цифровой наставник как инструмент формирования поддерживающей образовательной среды: от идеи – к созданию собственного чат-бота в организации",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/216%20ауд.%20Крикунова",
  },
  {
    name: "Мотуз Ирина",
    position: "",
    tag: "Организация мероприятий",
    topic: "Формула успешного события «Событие³» – мастер-класс",
    bullets: [],
    ppt: "https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2FAAaNLjCaxToCt5fJwuo16UuVbDj%2B0LwYinoOwpHIXKrkj%2F73c%2BiAsIBlfc%2FZ20twq%2FJ6bpmRyOJonT3VoXnDag%3D%3D%3A%2F214%20ауд.%20Мотуз.pptx&name=214%20ауд.%20Мотуз.pptx&nosw=1",
  },
  {
    name: "Сайферт Ирина",
    position: "",
    tag: "Командообразование",
    topic: "«5 островков неэффективности: практикум по построению сильных команд»",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/304%20ауд.%20Сайферт",
  },
  {
    name: "Шивырталова Елена",
    position: "",
    tag: "Профессиональное развитие",
    topic: "Мастер-класс «Пакет ПРОФИ активирован»",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/314%20ауд.%20Шивырталова",
  },
  {
    name: "Шульженко Анастасия",
    position: "",
    tag: "Методика",
    topic: "Игровая педагогика междисциплинарных уроков: создание рабочего листа для развития когнитивных способностей учащихся",
    bullets: [],
    ppt: "https://docs.yandex.ru/docs/view?url=ya-disk-public%3A%2F%2FAAaNLjCaxToCt5fJwuo16UuVbDj%2B0LwYinoOwpHIXKrkj%2F73c%2BiAsIBlfc%2FZ20twq%2FJ6bpmRyOJonT3VoXnDag%3D%3D%3A%2Fхолл%203%20этажа_Шульженко.pdf&name=холл%203%20этажа_Шульженко.pdf&nosw=1",
  },
  {
    name: "Ямилов Юрий",
    position: "",
    tag: "Мотивация",
    topic: "Мотивация – залог успеха!",
    bullets: [],
    ppt: "https://disk.yandex.ru/d/0nYYo2GP2mWcnw/316%20ауд_Ямилов%20Юрий%20Юрьевич",
  }
];
